name: static-deploy

on:
  push:
    branches:
      - main

jobs:
  static-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          echo "readme.radically.digital" >> CNAME
      - run: |
          echo "User-agent: *
            Disallow: /" >> robots.txt
      - run: npx surge .
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
